### ISSUE TITLE
Write a function that reverses a string

### ISSUE THREAD

**Issue by ryangjchandler** [Chandlz20057/PHP-LEARNING#2]
Write a function that accepts a string as an argument / parameter and reverses it. For example, `nameOfFunction('Hello')` should `echo` **olleH**.

**Comment by ryangjchandler** [comment]
Here's the basic structure:

```php
function reverse_string($string) {

}

reverse_string('Hello');
```

**Comment by ryangjchandler** [comment]
```php
for ($i = 0; $i < strlen($string); $i++) {
    $letter = $string[$i];
}
```

**Comment by Chandlz20057** [comment]
```php
function reverse_string($string){
strlen($string)
for ($i = 0; $i < strlen($string)> $i++); {
        $letter = $string[$i];
        
}
```

**Comment by ryangjchandler** [comment]
http://sandbox.onlinephpfunctions.com/code/1613a6ec7af619fef0762f30c43a53d4d8b78d81

**Comment by ryangjchandler** [comment]
Completed in https://github.com/Chandlz20057/PHP-LEARNING/commit/c5ff89eefa906808736b8f7cefc0030bba9dd8e9
