### ISSUE TITLE
Create a better contact form

### ISSUE THREAD

**Issue by ryangjchandler** [Chandlz20057/PHP-LEARNING#5]
Create a form that asks for your name, age and email address. 

Take that information and write it to a file called "submission.txt" in the same directory as your PHP script.

You need to research:

* [x] How to create a file with PHP
* [x] How to open a file with PHP
* [x] How to write to a file with PHP

**Comment by ryangjchandler** [comment]
Instead of:

```php
$path = 'folder/file.txt';
```

Do this:

```php
$path = 'folder' . DIRECTORY_SEPARATOR . 'file.txt';
```

**Comment by Chandlz20057** [comment]
closed by https://github.com/Chandlz20057/PHP-LEARNING/commit/b392d8631e29a81403282a7d23cb8f398516d995
