### ISSUE TITLE
Create a class that represents a family

### ISSUE THREAD

**Issue by ryangjchandler** [Chandlz20057/PHP-LEARNING#6]
I'd like you to create a class called `Family` that represents our family.

This class should have a _method_ that prints out the name of 7 family members.

* [x] Learn what a PHP class is.
* [x] Create your first class and construct a new object.
* [x] Create your first method.
* [x] Call your new method.

**Comment by Chandlz20057** [comment]
Closed by https://github.com/Chandlz20057/PHP-LEARNING/commit/707f68b13d2df00e76d36271022ece2988453ebd
