### ISSUE TITLE
Learn about abstract classes

### ISSUE THREAD

**Issue by ryangjchandler** [Chandlz20057/PHP-LEARNING#7]
Now that you know what a class is, how to instantiate a class and work with an object's properties and methods, I'd like you to research abstract classes.

You should be able to:
* [x] Write an abstract class
* [x] Write an abstract class with abstract methods
* [x] Use that abstract class on a child class and implement those abstract methods
* [x] Know the difference between `public`, `protected` and `private`.

**Comment by Chandlz20057** [comment]
closed by https://github.com/Chandlz20057/PHP-LEARNING/commit/0512c5c3ec1774a317993056a0f217b86a6791a6
