### ISSUE TITLE
Learn about interfaces

### ISSUE THREAD

**Issue by ryangjchandler** [Chandlz20057/PHP-LEARNING#8]
You should research interfaces in PHP. You should understand the following:

* [x] What an interface is.
* [x] What an interface does.
* [x] How to use / _implement_ an interface.

**Comment by ryangjchandler** [comment]
Here's a great video: https://www.youtube.com/watch?v=OItw_hOPewU

**Comment by Chandlz20057** [comment]
https://github.com/Chandlz20057/PHP-LEARNING/commit/be2a9ae1b379860ac8a914e221ceefd268d1e7d6

**Comment by ryangjchandler** [comment]
```php
public function listorders() {
    return ['Order 1', 'Order 2'];
}
```
